# CADI AI Training Configuration
# ================================
# This file contains all training parameters and paths.

# Model Configuration
model: "yolo11m.pt"  # Options: yolo11n.pt, yolo11s.pt, yolo11m.pt, yolo11l.pt, yolo11x.pt

# Data Configuration
data: "data.yaml"  # Path to your data.yaml file

# Training Parameters
epochs: 100
imgsz: 640
batch: "auto"  # Use "auto" for automatic batch size detection, or specify a number (e.g., 16)
device: 0  # GPU device (0 for first GPU, "cpu" for CPU)
workers: 8  # Number of data loading workers

# Training Behavior
patience: 50  # Early stopping patience (epochs without improvement)
save: true    # Save training checkpoints
plots: true   # Generate training plots
val: true     # Run validation during training

# Output Configuration
output_dir: "runs"  # Base directory for outputs
name: "cadi-training-2508"  # Experiment name

# Advanced Training Options (optional)
# Uncomment and modify as needed:

# optimizer: "auto"  # Optimizer: SGD, Adam, AdamW, NAdam, RAdam, RMSProp, auto
# lr0: 0.01          # Initial learning rate
# lrf: 0.01          # Final learning rate factor
# momentum: 0.937    # SGD momentum/Adam beta1
# weight_decay: 0.0005  # Optimizer weight decay
# warmup_epochs: 3   # Warmup epochs
# warmup_momentum: 0.8  # Warmup initial momentum
# warmup_bias_lr: 0.1   # Warmup initial bias lr

# Data Augmentation
# mosaic: 1.0        # Mosaic augmentation probability
# mixup: 0.0         # Mixup augmentation probability
# copy_paste: 0.0    # Copy-paste augmentation probability
# degrees: 0.0       # Image rotation (+/- deg)
# translate: 0.1     # Image translation (+/- fraction)
# scale: 0.5         # Image scale (+/- gain)
# shear: 0.0         # Image shear (+/- deg)
# perspective: 0.0   # Image perspective (+/- fraction), range 0-0.001
# flipud: 0.0        # Image flip up-down (probability)
# fliplr: 0.5        # Image flip left-right (probability)
# hsv_h: 0.015       # Image HSV-Hue augmentation (fraction)
# hsv_s: 0.7         # Image HSV-Saturation augmentation (fraction)
# hsv_v: 0.4         # Image HSV-Value augmentation (fraction)

# Loss Functions
# cls: 0.5           # Classification loss gain
# box: 7.5           # Box regression loss gain
# dfl: 1.5           # Distribution focal loss gain

# Model Architecture (for custom models)
# depth_multiple: 1.0   # Model depth scalar
# width_multiple: 1.0   # Model width scalar
